### ISSUE TITLE
the output of the demo.

### ISSUE THREAD

**Issue by qwerty863** [huangwl18/language-planner#2]
Hello, @huangwl18
First, I would like to thank you for sharing your awesome code!

I ran your demo without any change and this is what I got from the last cell (i.e., the **autoregressive plan generation** part) as below.
But it is a bit hard for me to find the output plan represents a possible solution (e.g., it tries to just open multiple objects but does not make some food).
Is this output expected (i.e., did you get that same output)? If not, what could be a reason for this?
```
---------- GIVEN EXAMPLE ----------
Task: Make toast
Step 1: Walk to dining room
Step 2: Walk to freezer
Step 3: Find freezer
Step 4: Open freezer
Step 5: Find food bread
Step 6: Grab food bread
Step 7: Close freezer
Step 8: Find toaster
Step 9: Plug in toaster
Step 10: Put food bread on toaster
Step 11: Switch on toaster
---------- EXAMPLE END ----------

Task: Make breakfast
Step 1: Walk to kitchen
Step 2: Turn to fridge
Step 3: Open fridge
Step 4: Open microwave
Step 5: Open oven
Step 6: Open stove
Step 7: Open cupboard

[Terminating early because best overall score is lower than CUTOFF_THRESHOLD (0.7268587350845337 < 0.8)]
```

Thank you!

**Comment by huangwl18** [comment]
Hi @qwerty863, if you didn't change any of the code, this is likely because the default language model used is just GPT-2, which is a relatively small language model but unfortunately is one of the few that can fit into most GPU. Changing to larger language model like GPT-3 should work a lot better, but this wasn't set as default to avoid unintended charges to your OpenAI account.

As of today, the best result can probably be achieved by using `text-davinci-002` from OpenAI. Look for the following two lines in the code to make this change:
```
source = 'openai'  # select from ['openai', 'huggingface']
planning_lm_id = 'text-davinci-002'  # see comments above for all options
```

**Comment by qwerty863** [comment]
I see. I'll try GPT-3 if I can. Thanks for quick replying!
Let me close the issue.
